apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo-git
  namespace: podinfo
spec:
  interval: 1m
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
  ignore: |
    # exclude all
    /*
    # include deploy dir
    !/kustomize
    # exclude non-Kubernetes YAMLs
    /kustomize/**/.yamllint.yaml
